name: Mahjong Helper actions
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies and run tests
        run: |
          npm i
          npm t
          npm run build
          npm run deploy
